arr_extension.lo: /home/johnny/program_files/php-7.0.25/ext/arr_extension/arr_extension.c
	$(LIBTOOL) --mode=compile $(CC) -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -I. -I/home/johnny/program_files/php-7.0.25/ext/arr_extension $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS)  -c /home/johnny/program_files/php-7.0.25/ext/arr_extension/arr_extension.c -o arr_extension.lo 
$(phplibdir)/arr_extension.la: ./arr_extension.la
	$(LIBTOOL) --mode=install cp ./arr_extension.la $(phplibdir)

./arr_extension.la: $(shared_objects_arr_extension) $(ARR_EXTENSION_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_arr_extension) $(ARR_EXTENSION_SHARED_LIBADD)

